osx_image: xcode8.3
sudo: false
language: node_js
node_js: '8'
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
os:
- osx
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.npm/_prebuilds"
  - "$HOME/.electron"
deploy:
  provider: releases
  api_key:
    secure: Z1WhEoZrVAWI6gk5/LZPZH5CyQ8e03XWh3xA39E7Jr2z2UP3m9rJz34MC+zTW8lLHGCxTn/YWXViaHVGzXsBQJD41G6jz1Fi9rKLyuBoCks0twZd4UXIE2ZBaYuJmj8oi9wuiYAbRJNkRi2spHPRCHZfhdbEouxSX3k68JMQciyjlANT8+jiI0JMzVS8PVyhD4ZUnLTre9fxontvpHlAPfKLVZLzq3vSRpbpCQQDBGijVbSj4YDYT6nN3IY+nllQt/tIE5WjNr3mIKDmbXxS76dcGC4AUkxOks7j9NmbjX3Rcsf3qm3SIr/J6goye5Si2MAOkwMDQ7YJkJACLXFPdU9zRA2X5F1g+SgSPt2Nt2c5n5a/G6M4kXPGiRPXYuPqPm0RPJ7PSstRUns2mZ/DOP0hHjMrbeQgpFHsszxiSI4CUhN+TyZsWNeW/1AtU4vSpPAkX9GetFr1kgixl0SN7kLJUe0QgJel9451L51y9JnLYyt97Wgb5WNE9mzMQGv2XeMGOWbhQXOgsUY81Y0giMN7Rz0/46LSczxKhztK1PMiE3a3NthdfoCrn9DW0L0dUS5ZqXosHMRq4e0bQzx5jQep3kMEfkCNpbd8CxT1FbZAUNvNrmttWnwTTtibV/ZhZ+AEylhIbZgW115WO9qvCLx0V8LFS303gj/kmiou/8M=
  skip_cleanup: true
  file: dist/Kegger.dmg
  on:
    tags: true
    repo: bealearts/kegger
