name: Build, Test and Publish

on:
  push:

env:
  CI: true

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: make all

      - name: Archive amd64
        uses: actions/upload-artifact@v4
        with:
          name: Kegger-amd64.dmg
          path: build/Kegger-amd64.dmg

      - name: Archive arm64
        uses: actions/upload-artifact@v4
        with:
          name: Kegger-arm64.dmg
          path: build/Kegger-arm64.dmg
      # - name: Test
      #   run: npm t

      # - name: Publish
      #   if: startsWith( github.ref, 'refs/tags/v')
      #   run: npm publish
