name: Build, Test and Publish

on:
  push:

env:
  CI: true

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-14]
        include:
          - os: macos-13
            arch: amd64
          - os: macos-14
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # - name: Test
      #   run: npm t

      - name: Build
        run: CGO_ENABLED=1 GOARCH=${{ matrix.arch }} make build

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: Kegger-${{ matrix.arch }}
          path: build/Kegger.dmg
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith( github.ref, 'refs/tags/v')

    steps:
      - name: Download Packages
        uses: actions/download-artifact@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload Release Asset - amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Kegger-amd64/Kegger.dmg
          asset_name: Kegger-amd64.dmg
          asset_content_type: application/octet-stream

      - name: Upload Release Asset - arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Kegger-arm64/Kegger.dmg
          asset_name: Kegger-arm64.dmg
          asset_content_type: application/octet-stream
