name: Build, Test and Publish

on:
  push:

env:
  CI: true

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.22

      # - name: Test
      #   run: npm t

      - name: Build
        run: make all

      - name: Archive amd64
        uses: actions/upload-artifact@v4
        with:
          name: Kegger-amd64.dmg
          path: build/Kegger-amd64.dmg

      - name: Archive arm64
        uses: actions/upload-artifact@v4
        with:
          name: Kegger-arm64.dmg
          path: build/Kegger-arm64.dmg

      - name: Create Release
        if: startsWith( github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: true

      - name: Upload Release Asset - amd64
        if: startsWith( github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/Kegger-amd64.dmg
          asset_name: Kegger-amd64.dmg
          asset_content_type: application/octet-stream

      - name: Upload Release Asset - arm64
        if: startsWith( github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/Kegger-arm64.dmg
          asset_name: Kegger-arm64.dmg
          asset_content_type: application/octet-stream
